version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      # Use this to pass env variables to react build.
      args:
        - API_BASE_URL=http://$MACHINE_HOST:$RESUME_SERVICE_PORT
    ports:
      - $FRONTEND_PORT:8080
  resume-service:
    build:
      context: ./resume-service
    ports:
      - 5000:80
      #- $RESUME_SERVICE_PORT:5000
